# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy.proto',
  package='easy',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\neasy.proto\x12\x04\x65\x61sy\"\x1c\n\tclientMSG\x12\x0f\n\x07request\x18\x01 \x01(\t\"\x1d\n\tserverMSG\x12\x10\n\x08response\x18\x01 \x01(\t2=\n\x0b\x65\x61syService\x12.\n\x08\x65\x61syCall\x12\x0f.easy.clientMSG\x1a\x0f.easy.serverMSG\"\x00\x62\x06proto3')
)




_CLIENTMSG = _descriptor.Descriptor(
  name='clientMSG',
  full_name='easy.clientMSG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='easy.clientMSG.request', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=48,
)


_SERVERMSG = _descriptor.Descriptor(
  name='serverMSG',
  full_name='easy.serverMSG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='easy.serverMSG.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['clientMSG'] = _CLIENTMSG
DESCRIPTOR.message_types_by_name['serverMSG'] = _SERVERMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

clientMSG = _reflection.GeneratedProtocolMessageType('clientMSG', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTMSG,
  __module__ = 'easy_pb2'
  # @@protoc_insertion_point(class_scope:easy.clientMSG)
  ))
_sym_db.RegisterMessage(clientMSG)

serverMSG = _reflection.GeneratedProtocolMessageType('serverMSG', (_message.Message,), dict(
  DESCRIPTOR = _SERVERMSG,
  __module__ = 'easy_pb2'
  # @@protoc_insertion_point(class_scope:easy.serverMSG)
  ))
_sym_db.RegisterMessage(serverMSG)



_EASYSERVICE = _descriptor.ServiceDescriptor(
  name='easyService',
  full_name='easy.easyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=81,
  serialized_end=142,
  methods=[
  _descriptor.MethodDescriptor(
    name='easyCall',
    full_name='easy.easyService.easyCall',
    index=0,
    containing_service=None,
    input_type=_CLIENTMSG,
    output_type=_SERVERMSG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EASYSERVICE)

DESCRIPTOR.services_by_name['easyService'] = _EASYSERVICE

# @@protoc_insertion_point(module_scope)
