# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import easy_pb2 as easy__pb2


class easyServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.easyCall = channel.unary_unary(
        '/easy.easyService/easyCall',
        request_serializer=easy__pb2.clientMSG.SerializeToString,
        response_deserializer=easy__pb2.serverMSG.FromString,
        )


class easyServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def easyCall(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_easyServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'easyCall': grpc.unary_unary_rpc_method_handler(
          servicer.easyCall,
          request_deserializer=easy__pb2.clientMSG.FromString,
          response_serializer=easy__pb2.serverMSG.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'easy.easyService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
